#!/usr/bin/perl

# TODO: Trap signals and delete temporary keyring

my $keyid;
if (defined $ARGV[0] and $ARGV[0] =~ /^[0-9a-fA-F]{8}$/) {
    $keyid = shift;
}
else {
    die "Usage: $0 key args...\n";
}

my $tmp_keyring = "$ENV{HOME}/$keyid-keyring.gpg";

system 'gpg', '--no-default-keyring', '--keyring', $tmp_keyring, '--recv-keys', $keyid;
system 'gpg', '--no-default-keyring', '--keyring', $tmp_keyring, @ARGV;
unlink $tmp_keyring;
